name: googleNewsFede
description: A new Flutter project.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  webview_flutter: ^0.3.19+9
  url_launcher: ^5.1.4
  url_launcher_web: ^0.1.1+1
  share: ^0.6.4
  cupertino_icons: ^0.1.3
  test: ^1.14.2
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  dio_flutter_transformer: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - default-image.jpg
